name: Deploy Backend

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Docker image tag (e.g: v0.0.1)'
        required: false
        type: string

env:
  IMAGE_NAME: cohere-toolkit-backend

jobs:
  build-and-push-backend-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:

      - name: Login
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          service_account_email: deploy-a-thing@minimap-v0.iam.gserviceaccount.com
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Checkout repository
        uses: actions/checkout@v2

      - run: 'echo "$KEY" > ./key.json'
        shell: bash
        env:
          KEY: ${{ secrets.GCP_SA_KEY }}

      - name: Checkout code
        uses: actions/checkout@v2

      # Deploy the image to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.IMAGE_NAME }} \
            --project=${{ vars.GCP_PROJECT_ID }} \
            --image=${{ steps.meta.outputs.tags }} \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated \
            --update-env-vars=DATABASE_URL=${{ secrets.DATABASE_URL }},COHERE_API_KEY=${{ secrets.COHERE_API_KEY }} \
            --memory=4Gi \
            --cpu=4 \
            --max-instances=1
